{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "memberRoleAdd",
    "content": "712686968592400446"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{user.removerole; No Roles}",
      "channel": "712663327402229791",
      "id": "5ee67399ea2c3e0026eb5e04"
    }
  ],
  "formatVersion": "1.2"
}