{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "keyword",
    "content": "need to revise"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{if; {replace; {lower; {message.content}}; need to revise.*$; need to revise}; == ; need to revise;\n{if; {find; {user.roles}; {role.id; Revising}}; == ; {role.id; Revising}; You are already in revision mode! Type \"finished revising\" to exit revision mode.;\n{user.addrole; Revising}\nYou have entered revision mode! Type \"finished revising\" to exit revision mode}}",
      "id": "5eee0809a52578002654507d"
    }
  ],
  "formatVersion": "1.2"
}