{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "keyword",
    "content": "finished revising"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{if; {replace; {lower; {message.content}}; finished revising.*$; finished revising}; == ; finished revising;\n{if; {find; {user.roles}; {role.id; Revising}}; == ; {role.id; Revising};\n{user.removerole; Revising} You have exited revision mode! Hope you got something useful done!; You aren't in revision mode! Type \"need to revise\" to enter revision mode.}}",
      "id": "5eee0811a52578002654507e"
    }
  ],
  "formatVersion": "1.2"
}